liip_imagine :
    resolvers :
        default :
            web_path : ~
    filter_sets :
        cache : ~
        my_thumb :
            quality : 75
            filters :
                thumbnail  : { size : [360, 270], mode : outbound }

