liip_imagine :
    resolvers :
        default :
            web_path : ~
    filter_sets :
        cache : ~
        my_thumb :
            quality : 75
            filters :
                thumbnail  : { size : [360, 270], mode : outbound }
        medium :
            quality : 75
            filters :
                thumbnail  : { size : [800, 530], mode : outbound }
        home_card :
            quality : 75
            filters :
                thumbnail  : { size : [640, 427], mode : outbound }


