twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
    # Création de la route css pour injecter les fichier dans le inliner_css des email
        '%kernel.project_dir%/public/css': css
when@test:
    twig:
        strict_variables: true
